### ISSUE TITLE
PNG export adds additional black padding

### ISSUE THREAD

**Issue by WeForgot** [malulleybovo/SymbolArtEditorOnline#9] opened 2020-06-15 18:06 UTC
Using this as an example
https://wikiwiki.jp/pso2sa/sa13#sa46
When you export an imported .sar or .saml file as a .png you get a small black boarder spanning the top and left sides.
![御坂みこと](https://user-images.githubusercontent.com/6954125/84689763-71647280-af0f-11ea-97c4-435f5069df6f.png)
The output image size is 576x288 which is still a multiple of 192x96 but I am unsure where it is cutting the image off at (eyeballing it, I cannot see if it is shifting it or just setting the sides to black).

**Comment by WeForgot** [comment] 2020-06-19 15:28
Found a workaround but I am not comfortable requesting any sort of commit on this given magic numbers and my lack of understanding the code (or ability programming in JS). If you change these two lines:
https://github.com/malulleybovo/SymbolArtEditorOnline/blob/f6278533f6b96217b92d9286141a94e8cb5d2150/js/main.js#L342-L343
to be -3 each then everything works correctly. I have random ideas why it happens this way but, as I said, I am no pro at either this code base or JS so I will refrain from spouting nonsense :^)

**Comment by malulleybovo** [comment] 2020-06-20 03:27
Thanks for reporting this issue and even looking into the cause of it. That does seem to be a bug. I will investigate this. 
About this project's code base, in all honesty, I rushed the architecture planning and focused more on reverse-engineering and implementation so it's so much more unorganized than my professional work. That now impacts the maintenance of the project to the point that I considered restarting from near scratch (if I had the will and time to do it since it grew quite big). So it's understandable to be fairly hard to understand if you're not familiar with the project.
In any case, in general, if you're confident you have found the solution to a bug in the project, feel more than free to send a pull request.

**Comment by malulleybovo** [comment] 2020-06-20 08:55
The bug has been fixed in the latest version.

**Closed by malulleybovo** 2020-06-20 08:55 UTC
Labels: bug
