### ISSUE TITLE
Can't Change Color

### ISSUE THREAD

**Issue by jstenmoe** [malulleybovo/SymbolArtEditorOnline#7] opened 2020-06-09 17:59 UTC
When selecting a symbol and attempting to change the color via the menu in the bottom-right, nothing changes. All symbols I add are stuck as white.

**Comment by malulleybovo** [comment] 2020-06-12 05:24
Thank you for reporting this issue. There has been quite a few issues of this nature being reported so I will guess the solution is the same:

As I mentioned in other issues (https://github.com/malulleybovo/SymbolArtEditorOnline/issues/2 https://github.com/malulleybovo/SymbolArtEditorOnline/issues/5), there is an unspoken requirement for hardware acceleration while running the editor (which modern browsers set as default) since the application deals with graphic computation, and that benefits from hardware acceleration. Please make sure you have hardware acceleration enabled (in Settings of your browser of preference) while running the editor to avoid unexpected behavior such as what you reported. Note that upon changing this setting in the browser, they normally require you to restart the browser.

In Chrome, that is in Settings->Advanced->System->Use hardware acceleration when available.
Without this setting enabled, some features don't fully work as expected (such as transparency and coloring). Although I am uncertain that the application will ever be compatible with this setting off, I might look for a way to make it clearer that you do need to turn this setting on to minimize frustration. For now, I suggest you try enabling the setting and trying again. I hope that helps!

**Comment by malulleybovo** [comment] 2020-06-12 07:48
Since there seems to be an increasing number of issues of this nature, I decided to include a warning in the application to guide users to enable Hardware Acceleration in case they have it disabled before they are faced with this issue. I will be closing this issue then.

**Closed by malulleybovo** 2020-06-12 07:48 UTC
