### ISSUE TITLE
Unable to import saved .sar file into PSO2

### ISSUE THREAD

**Issue by jzkzy** [malulleybovo/SymbolArtEditorOnline#6] opened 2020-06-04 12:56 UTC
Great tool, thx. Isssue: Once I've downloaded the symbol art, I place the file in the import folder. Click import in game, click the image and try to save it to a slot. I get the follow error code from pso2 Na server. "Unable to save because the symbol art data is invalid. [No.1210] .

Any idea ? I downloaded it using google chrome. I see it in game but it won't allow me to save it to a slot.

**Comment by malulleybovo** [comment] 2020-06-07 06:38
Thank you for reporting the issue. First and foremost, please understand that this application was made entirely based on the Japanese version of the game so there might be compatibility issues that I am unaware of. With that said:
1) Does this happen with any Symbol Art you save as .sar and place in the import folder? Or does it happen with a particular file?
2) Are you able to load this .sar file within the editor and see the image without inaccuracies? (by opening the Symbol Art Editor Online and clicking the import icon next to the "+")
3) Would you mind sharing the .sar file you are trying to import?

**Comment by jzkzy** [comment] 2020-06-07 22:33
[cosmos (3).zip](https://github.com/malulleybovo/SymbolArtEditorOnline/files/4743144/cosmos.3.zip)

**Comment by jzkzy** [comment] 2020-06-07 22:33
at import

i can load it into the editor

**Comment by malulleybovo** [comment] 2020-06-12 05:05
Hello again. It seems like I found the source of the problem. Every type of symbol in the editor has a unique identifier, but it seems the SA Editor Online has at least one symbol with an incorrect identifier. There might be more such symbols, so I'll try my best to inspect this as soon as I can.
The offending symbol identified:
![image](https://user-images.githubusercontent.com/14852459/84466868-0c272d80-ac40-11ea-8f42-4f6ba2512970.png)
The .sar you attached (thank you for sharing) has two layers (layer 92 and layer 93) using this one symbol and the game wont recognize that incorrect symbol, thus the error you receive in game.

In my testing, I did produce a working version of your SA and I am attaching it in this comment (in case you want it) since you wont be able to use this symbol until the SA Editor Online is fixed. This .sar I am attaching was tested on the JP version of the game and it is importing and saving correctly.
Note that if you load this .sar in the SA Editor Online, layers 92 and 93 will show as blank due to the yet unsupported symbol.

[cosmos.zip](https://github.com/malulleybovo/SymbolArtEditorOnline/files/4768857/cosmos.zip)

Thank you once again for reporting.

**Comment by usagirei** [comment] 2020-06-18 16:18
The problem is these 5 symbols in particular

![image](https://user-images.githubusercontent.com/12700106/85045308-2e9bd800-b165-11ea-81d5-d26aee304222.png)

Your editor IDs are 705 ... 709, but their IDs are 609 ... 613 in game, since they actually come before the first symbol on the texture atlas (there's more than that that, but the atlas isn't exactly ordered as you'd guess, its sequential at least, but not without gaps in ids)

![image](https://user-images.githubusercontent.com/12700106/85045619-93efc900-b165-11ea-9218-2851e9ab2c01.png)

Marks001 (ID 641):
![image](https://user-images.githubusercontent.com/12700106/85045658-a4a03f00-b165-11ea-9099-b2b4f0a8b065.png)

**Comment by malulleybovo** [comment] 2020-06-21 19:14
@usagirei thanks for investigating this, I double checked it and indeed it is these exact five symbols that were incorrect. This issue has been fixed in the latest version.

**Closed by malulleybovo** 2020-06-21 19:14 UTC
Labels: bug
