### ISSUE TITLE
Toggling transparency

### ISSUE THREAD

**Issue by Henry715** [malulleybovo/SymbolArtEditorOnline#5] opened 2020-06-04 07:26 UTC
I don't know if it's because the picture I used, the picture itself is 192*96, but after I upload the picture, the transparency was not changed at all. The transparency slide is like a switch, it's either fully transparent or it's solid and can not be seen through.

**Comment by Henry715** [comment] 2020-06-04 07:26
Great tools you made by the way, it's really helpful.

**Comment by malulleybovo** [comment] 2020-06-07 06:26
Thank you reporting the issue. I will need more information to identify the cause of this issue as I was unable to reproduce this issue.
1) In which browser did you face this issue? Google Chrome, Firefox, Opera, ...? Did it happen on other browsers?
2) In which operating system did you face this issue? Windows, Mac, iOS, Android?
3) What is the image type you used that had this problem? JPG, PNG, ...?
4) When dragging the "transparency" bar on the top right corner, you mean that if the bar is at least partially complete the image shows as solid? What values of transparency make it completely transparent and which values make it solid?
5) Does the issue persist after re-importing the image by clicking on the "+" icon, importing again, then dragging the transparency bar again?
![image](https://user-images.githubusercontent.com/14852459/83599691-32174880-a543-11ea-9a1d-ff1d2704f125.png)![image](https://user-images.githubusercontent.com/14852459/83599803-7d315b80-a543-11ea-9893-58ab5d3ce82a.png)

Lastly, note that I maintain this repository as a hobby only so any effort put in it is out of my own free time and will. So I cannot promise any deadlines for when this will be fixed. I hope everyone can understand.

**Comment by Henry715** [comment] 2020-06-07 09:47
Dear author,So I am using Google Chrome, I haven’t tested on other browsers yet, OS version is Win10, with latest updates installed.The extension of the image I used is JPG, when I Dragging the bar, the lowest value will make the pic totally transparent, as long as the transparency bar has some value, it will be solid, which I just record this and send you a copy of this phenomenon( and also the pic, don’t know if it’s because the pic itself), and yes, no matter how many times I import it again, it’s still the same. Truly appreciate your works, thank you. Best regards,Henry 发件人: malulleybovo发送时间: 2020年6月7日 7:26收件人: malulleybovo/SymbolArtEditorOnline抄送: Henry715; Author主题: Re: [malulleybovo/SymbolArtEditorOnline] Toggling transparency (#5) Thank you reporting the issue. I will need more information to identify the cause of this issue as I was unable to reproduce this issue.In which browser did you face this issue? Google Chrome, Firefox, Opera, ...? Did it happen on other browsers?In which operating system did you face this issue? Windows, Mac, iOS, Android?What is the image type you used that had this problem? JPG, PNG, ...?When dragging the "transparency" bar on the top right corner, you mean that if the bar is at least partially complete the image shows as solid? What values of transparency make it completely transparent and which values make it solid?Does the issue persist after re-importing the image by clicking on the "+" icon, importing again, then dragging the transparency bar again?Lastly, note that I maintain this repository as a hobby only so any effort put in it is out of my own free time and will. So I cannot promise any deadlines for when this will be fixed. I hope everyone can understand.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Henry715** [comment] 2020-06-07 09:49
Dear author,And forgot to mention, the version of Chrome I have is  83.0.4103.61. Best regards,Henry  发件人: malulleybovo发送时间: 2020年6月7日 7:26收件人: malulleybovo/SymbolArtEditorOnline抄送: Henry715; Author主题: Re: [malulleybovo/SymbolArtEditorOnline] Toggling transparency (#5) Thank you reporting the issue. I will need more information to identify the cause of this issue as I was unable to reproduce this issue.In which browser did you face this issue? Google Chrome, Firefox, Opera, ..? Did it happen on other browsers?In which operating system did you face this issue? Windows, Mac, iOS, Android?What is the image type you used that had this problem? JPG, PNG, ...?When dragging the "transparency" bar on the top right corner, you mean that if the bar is at least partially complete the image shows as solid? What values of transparency make it completely transparent and which values make it solid?Does the issue persist after re-importing the image by clicking on the "+" icon, importing again, then dragging the transparency bar again?Lastly, note that I maintain this repository as a hobby only so any effort put in it is out of my own free time and will. So I cannot promise any deadlines for when this will be fixed. I hope everyone can understand.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by malulleybovo** [comment] 2020-06-12 03:05
Hello again. I did not see the attachments you mentioned since I take it you replied via email instead of GitHub Issues (and I did not receive the email, so I read it on GitHub Issues). However, I may have found the source of the problem. As I mentioned in another issue (https://github.com/malulleybovo/SymbolArtEditorOnline/issues/2):

There is an unspoken requirement for hardware acceleration while running the editor (which modern browsers set as default) since the application deals with graphic computation, and that benefits from hardware acceleration. Please make sure you have hardware acceleration enabled (in Settings of your browser of preference) while running the editor to avoid unexpected behavior such as what you reported. Note that upon changing this setting in the browser, they normally require you to restart the browser.

In Chrome, that is in Settings->Advanced->System->Use hardware acceleration when available.
Without this setting enabled, some features don't fully work as expected (such as transparency and coloring). Although I am uncertain that the application will ever be compatible with this setting off, I might look for a way to make it clearer that you do need to turn this setting on to minimize frustration. For now, I suggest you try enabling the setting and trying again. I hope that helps!

**Comment by Henry715** [comment] 2020-06-12 04:22
Dear author,      Great, so problem solved, it is because of the hardware acceleration that cause the problem, now it does its job nicely, thank you very much. Best regards,Henry 发件人: malulleybovo发送时间: 2020年6月12日 4:05收件人: malulleybovo/SymbolArtEditorOnline抄送: Henry715; Author主题: Re: [malulleybovo/SymbolArtEditorOnline] Toggling transparency (#5) Hello again. I did not see the attachments you mentioned since I take it you replied via email instead of GitHub Issues (and I did not receive the email, so I read it on GitHub Issues). However, I may have found the source of the problem. As I mentioned in another issue (#2):There is an unspoken requirement for hardware acceleration while running the editor (which modern browsers set as default) since the application deals with graphic computation, and that benefits from hardware acceleration. Please make sure you have hardware acceleration enabled (in Settings of your browser of preference) while running the editor to avoid unexpected behavior such as what you reported. Note that upon changing this setting in the browser, they normally require you to restart the browser.In Chrome, that is in Settings->Advanced->System->Use hardware acceleration when available.Without this setting enabled, some features don't fully work as expected (such as transparency and coloring). Although I am uncertain that the application will ever be compatible with this setting off, I might look for a way to make it clearer that you do need to turn this setting on to minimize frustration. For now, I suggest you try enabling the setting and trying again. I hope that helps!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by malulleybovo** [comment] 2020-06-12 07:48
It is great to hear that solved the issue. Since there seems to be an increasing number of issues of this nature, I decided to include a warning in the application to guide users to enable Hardware Acceleration in case they have it disabled before they are faced with this issue. I will be closing this issue then.

**Closed by malulleybovo** 2020-06-12 07:48 UTC
